  version: "3.3"

  services:

    mysql:
      image: mysql:8.0
      container_name: mysql
      ports:
        - "3306:3306"
      command: --init-file /data/application/init.sql
      volumes:
        - ./init.sql:/data/application/init.sql
      environment:
        - MYSQL_DATABASE=keycloak
        - MYSQL_USER=keycloak
        - MYSQL_PASSWORD=password
        - MYSQL_ROOT_PASSWORD=root_password
      healthcheck:
        test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"

    keycloak:
      image: quay.io/keycloak/keycloak:20.0.1
      container_name: keycloak
      environment:
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
        - KC_DB=mysql
        - KC_DB_URL_HOST=mysql
        - KC_DB_URL_DATABASE=keycloak
        - KC_DB_USERNAME=keycloak
        - KC_DB_PASSWORD=password
      ports:
        - "9090:8080"
      command: start-dev
      depends_on:
        - mysql
      healthcheck:
        test: "curl -f http://localhost:9090/admin || exit 1"

    app:
      image: 'docker-spring-boot-postgres:latest'
      build:
        context: .
      container_name: app
      ports:
        - "8080:8080"
      command:
        - ./mvnw clean package -DskipTests
        - cp target/godzilla.jar src/main/docker
      depends_on:
        - mysql
        - keycloak
      environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/godzilladbdemo
        - SPRING_DATASOURCE_USERNAME=godzillauserdemo
        - SPRING_DATASOURCE_PASSWORD=godzillapassdemo
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update