  version: "3.3"

  services:
    mysql:
      image: mysql:8.0
      container_name: mysql
      ports:
        - "3306:3306"
      command: --init-file /data/application/init.sql
      volumes:
        - ./init.sql:/data/application/init.sql
      environment:
        - MYSQL_DATABASE=keycloak
        - MYSQL_USER=keycloak
        - MYSQL_PASSWORD=password
        - MYSQL_ROOT_PASSWORD=root_password
      healthcheck:
        test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"

    keycloak:
      image: quay.io/keycloak/keycloak:20.0.3
      container_name: keycloak
      volumes:
#        - /mnt/c/Users/vtanh/Documents/Projects/DemoGodzilla/keycloak:/home
        - ./keycloak/DemoGodZilla-realm.json:/opt/jboss/keycloak/imports/DemoGodZilla-realm.json
      environment:
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
        - KC_DB=mysql
        - KC_DB_URL_HOST=mysql
        - KC_DB_URL_DATABASE=keycloak
        - KC_DB_USERNAME=keycloak
        - KC_DB_PASSWORD=password
      ports:
        - "9090:9090"
      command:
        - "-Dkeycloak.import=/opt/jboss/keycloak/imports/DemoGodZilla-realm.json"
        - "start-dev --http-port 9090"
      depends_on:
        - mysql
      healthcheck:
        test: "curl -f http://localhost:9090/admin || exit 1"
#
#    app:
#      image: 'docker-spring-boot-postgres:latest'
#      build:
#        context: .
#      container_name: app
#      ports:
#        - "8080:8080"
#      depends_on:
#        - keycloak
